### This script is not meant to be executed its merley a template that
### Should be filled out and saved inside of a directory called secret
### as keys.py

## To create the Flask_Key use python import os os.urandom(45)
## To obtain Keys (consumer_secret, access_secret, access_token, consumer_key)
## Go to https://dev.twitter.com/apps/new and grab some keys


def key():

    keys = {
        'Flask_Key': 'REPLACE WITH A KEY GENERATED BY OS',
        'consumer_secret': "REPLACE ME",
        'access_secret': "REPLACE ME",
        'access_token': "REPLACE ME",
        'consumer_key': "REPLACE ME"
    }


